---
apiVersion: apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: hive-cluster-gitrepo
spec:
#  tower_auth_secret: my-toweraccess
  job_template_name: print
  extra_vars:
    variable1: value1
    variable2: value2
